package org.tb.bdom;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Bean for table 'vacation'
 * 
 * @author oda
 */
@Entity
public class Vacation implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Autogenerated technical object id.
	 */	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;

	/** Employeecontract */
	@ManyToOne
	@JoinColumn(name="EMPLOYEECONTRACT_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Employeecontract employeecontract;
	
	/** year */
	private Integer year;
	
	/** entitlement */
	private Integer entitlement;
	
	/** used */
	private Integer used;
	

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public Employeecontract getEmployeecontract() {
		return employeecontract;
	}

	public void setEmployeecontract(Employeecontract employeecontract) {
		this.employeecontract = employeecontract;
	}

	public Integer getEntitlement() {
		return entitlement;
	}

	public void setEntitlement(Integer entitlement) {
		this.entitlement = entitlement;
	}

	public Integer getUsed() {
		return used;
	}

	public void setUsed(Integer used) {
		this.used = used;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Vacation) {
			Vacation other = (Vacation) obj;
			return (other.year.equals(year) && other.employeecontract.equals(employeecontract));
		}
		return false;
	}

}
