version: "3.9"  # optional since v1.27.0
services:
  salat:
    image: ghcr.io/hbtgmbh/salat:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: salattest
      SPRING_DATASOURCE_PASSWORD: salattest
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/salat?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1024M
