server:
  tomcat:
    resource:
      allow-caching: true
      cache-ttl: '1m'
spring:
  web:
    resources:
      cache:
        period: '1m'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://login.microsoftonline.com/0af2c34e-4e40-42d9-89ab-e095b8151308/v2.0'
salat:
  auth:
    refresh:
      enabled: true
    api-scope: 'api://865b95c4-f360-4ca2-ba20-4fe28e3ea4f6/user_impersonation'