
server:
  servlet:
    session:
      persistent: false
      timeout: 12h
      cookie:
        same-site: strict
        name: SALATSESSIONID
        secure: true
  forward-headers-strategy: native # ensure correct handling of X-Forwarded-Host and X-Forwarded-Proto headers
  max-http-request-header-size: 256KB
  error:
    include-stacktrace: never
    include-message: always
    include-exception: false
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/salat?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false&autoReconnect=true
    username: salattest
    password: salattest
    hikari:
      connection-timeout: 1000
      minimum-idle: 0
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    open-in-view: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
      static-locations:
        - /style/
        - /scripts/
        - /images/
management:
  endpoints:
    web:
      exposure:
        include: health
salat:
  auth:
    logout:
      enabled: true
      logout-url: /?logout=true
    refresh:
      enabled: false
      refresh-url: /.auth/refresh
  url: localhost
  mail-host: localhost
  auth-service:
    cache-expiry: 1s
  cache:
    max-entries: 1000
    expiry-tti: 10
springdoc:
  swagger-ui:
    path: /api/doc/
    try-it-out-enabled: true
  api-docs:
    path: /api/doc/api-docs
  default-produces-media-type: application/json