server:
  servlet:
    session:
      persistent: false
      timeout: 660m
  forward-headers-strategy: native # ensure correct handling of X-Forwarded-Host and X-Forwarded-Proto headers
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/salat?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false&autoReconnect=true
    username: salattest
    password: salattest
    hikari:
      connection-timeout: 1000
      minimum-idle: 0
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    open-in-view: true
    database: mysql

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
salat:
  url: localhost
  mail-host: localhost
  auth-service:
    cache-expiry: 5m
