server:
  tomcat:
    resource:
      allow-caching: true
      cache-ttl: 1d
  servlet:
    session:
      persistent: false
      timeout: 660m
  error:
    whitelabel:
      enabled=false:
  forward-headers-strategy: native # ensure correct handling of X-Forwarded-Host and X-Forwarded-Proto headers
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salat?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false&autoReconnect=true
    username: salattest
    password: salattest
    hikari:
      connection-timeout: 1000
      minimum-idle: 0
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    open-in-view: true
    database: mysql
  web:
    resources:
      cache:
        period: 1d
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_AD_TENANT_ID} # TODO use Key-vault
        credential:
          client-id: ${AZURE_AD_CLIENT_ID} # TODO use Key-vault
          client-secret: ${AZURE_AD_CLIENT_SECRET} # TODO use Key-vault
#      keyvault:
#        secret:
#          endpoint: https://salat-key-vault.vault.azure.net/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
salat:
  url: localhost
  mail-host: localhost
  auth-service:
    cache-expiry: 5m
