
server:
  servlet:
    session:
      persistent: false
      timeout: 12h
      cookie:
        same-site: strict
        name: SALATSESSIONID
        secure: true
  forward-headers-strategy: native # ensure correct handling of X-Forwarded-Host and X-Forwarded-Proto headers
  max-http-request-header-size: 256KB
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/salat?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false&autoReconnect=true
    username: salattest
    password: salattest
    hikari:
      connection-timeout: 1000
      minimum-idle: 0
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    open-in-view: true
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
      static-locations:
        - /style/
        - /scripts/
management:
  endpoints:
    web:
      exposure:
        include: health
salat:
  auth:
    refresh:
      enabled: false
      refresh-url: /.auth/refresh
  url: localhost
  mail-host: localhost
  auth-service:
    cache-expiry: 1s
springdoc:
  swagger-ui:
    path: /rest/doc/
    try-it-out-enabled: true
  api-docs:
    path: /rest/doc/api-docs
  default-produces-media-type: application/json