spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_AD_TENANT_ID} # TODO use Key-vault
        credential:
          client-id: ${AZURE_AD_CLIENT_ID} # TODO use Key-vault
          client-secret: ${AZURE_AD_CLIENT_SECRET} # TODO use Key-vault
        # user-name-attribute:

#      keyvault:
#        secret:
#          endpoint: https://salat-key-vault.vault.azure.net/
