server:
  servlet:
    session:
      persistent: false
      timeout: 660m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salat?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false
    username: salattest
    password: salattest
    hikari:
      connection-timeout: 1000
      minimum-idle: 0
      maximum-pool-size: 2
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
salat:
  url: localhost
  mail-host: localhost
