package org.tb.bdom;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.*;

import javax.persistence.Entity;
import javax.persistence.*;
import java.io.Serializable;

@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class ProjectID implements Serializable {

    private static final long serialVersionUID = 1L; // 1L;

    /**
     * Autogenerated technical object id.
     */
    @Id
    @GeneratedValue
    private long id;

    /**
     * Customerorder
     */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "CUSTOMERORDER_ID")
    @Cascade(value = {CascadeType.SAVE_UPDATE})
    private Customerorder customerorder;

    /**
     * Jira-Project-ID
     */
    @Column(name = "jira_Project_ID")
    private String jiraProjectID;

    /**
     * @return the customerorder
     */
    public Customerorder getCustomerorder() {
        return customerorder;
    }

    /**
     * @param customerorder - the customerorder to set
     */
    public void setCustomerorder(Customerorder customerorder) {
        this.customerorder = customerorder;
    }

    /**
     * @return the id
     */
    public long getId() {
        return id;
    }

    /**
     * @param id - the id to set
     */
    public void setId(long id) {
        this.id = id;
    }

    public String getJiraProjectID() {
        return jiraProjectID;
    }

    public void setJiraProjectID(String jiraProjectID) {
        this.jiraProjectID = jiraProjectID;
    }

}
