package org.tb.bdom;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * 
 * Bean for table 'statusreport'
 * 
 * @author th
 *
 */
@Entity
@Table(name = "STATUSREPORT")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Statusreport implements Serializable {
    
    private static final long serialVersionUID = 1L; // 3L;
    
    /**
     * Autogenerated technical object id.
     */
    @Id
    @GeneratedValue
    private long id;
    
    /** Customer order */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "CUSTOMERORDER")
    @Cascade(value = { CascadeType.SAVE_UPDATE })
    private Customerorder customerorder;
    
    /** Sender */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "SENDER")
    private Employee sender;
    
    /** Recipient */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "RECIPIENT")
    private Employee recipient;
    
    /** Released by */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "RELEASEDBY")
    private Employee releasedby;
    
    /** Accepted by */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "ACCEPTEDBY")
    private Employee acceptedby;
    
    private Byte sort;
    private Byte phase;
    private java.sql.Date fromdate;
    private java.sql.Date untildate;
    private String allocator;
    private Byte trend;
    private Byte trendstatus;
    private String needforaction_text;
    private String needforaction_source;
    private Byte needforaction_status;
    private String aim_text;
    private String aim_source;
    private String aim_action;
    private Byte aim_status;
    private String budget_resources_date_text;
    private String budget_resources_date_source;
    private String budget_resources_date_action;
    private Byte budget_resources_date_status;
    private String riskmonitoring_text;
    private String riskmonitoring_source;
    private String riskmonitoring_action;
    private Byte riskmonitoring_status;
    private String changedirective_text;
    private String changedirective_source;
    private String changedirective_action;
    private Byte changedirective_status;
    private String communication_text;
    private String communication_source;
    private String communication_action;
    private Byte communication_status;
    private String improvement_text;
    private String improvement_source;
    private String improvement_action;
    private Byte improvement_status;
    private String customerfeedback_text;
    private String customerfeedback_source;
    private Byte customerfeedback_status;
    private String miscellaneous_text;
    private String miscellaneous_source;
    private String miscellaneous_action;
    private Byte miscellaneous_status;
    private String notes;
    private java.util.Date released;
    private java.util.Date accepted;
    private java.util.Date created;
    private String createdby;
    private java.util.Date lastupdate;
    private String lastupdatedby;
    private Integer updatecounter;
    
    /**
     * @return the accepted
     */
    public java.util.Date getAccepted() {
        return accepted;
    }
    
    /**
     * @param accepted the accepted to set
     */
    public void setAccepted(java.util.Date accepted) {
        this.accepted = accepted;
    }
    
    /**
     * @return the acceptedby
     */
    public Employee getAcceptedby() {
        return acceptedby;
    }
    
    /**
     * @param acceptedby the acceptedby to set
     */
    public void setAcceptedby(Employee acceptedby) {
        this.acceptedby = acceptedby;
    }
    
    /**
     * @return the aim_action
     */
    public String getAim_action() {
        return aim_action;
    }
    
    /**
     * @param aim_action the aim_action to set
     */
    public void setAim_action(String aim_action) {
        this.aim_action = aim_action;
    }
    
    /**
     * @return the aim_source
     */
    public String getAim_source() {
        return aim_source;
    }
    
    /**
     * @param aim_source the aim_source to set
     */
    public void setAim_source(String aim_source) {
        this.aim_source = aim_source;
    }
    
    /**
     * @return the aim_status
     */
    public Byte getAim_status() {
        return aim_status;
    }
    
    /**
     * @param aim_status the aim_status to set
     */
    public void setAim_status(Byte aim_status) {
        this.aim_status = aim_status;
    }
    
    /**
     * @return the aim_text
     */
    public String getAim_text() {
        return aim_text;
    }
    
    /**
     * @param aim_text the aim_text to set
     */
    public void setAim_text(String aim_text) {
        this.aim_text = aim_text;
    }
    
    /**
     * @return the allocator
     */
    public String getAllocator() {
        return allocator;
    }
    
    /**
     * @param allocator the allocator to set
     */
    public void setAllocator(String allocator) {
        this.allocator = allocator;
    }
    
    /**
     * @return the budget_resources_date_action
     */
    public String getBudget_resources_date_action() {
        return budget_resources_date_action;
    }
    
    /**
     * @param budget_resources_date_action the budget_resources_date_action to set
     */
    public void setBudget_resources_date_action(String budget_resources_date_action) {
        this.budget_resources_date_action = budget_resources_date_action;
    }
    
    /**
     * @return the budget_resources_date_source
     */
    public String getBudget_resources_date_source() {
        return budget_resources_date_source;
    }
    
    /**
     * @param budget_resources_date_source the budget_resources_date_source to set
     */
    public void setBudget_resources_date_source(String budget_resources_date_source) {
        this.budget_resources_date_source = budget_resources_date_source;
    }
    
    /**
     * @return the budget_resources_date_status
     */
    public Byte getBudget_resources_date_status() {
        return budget_resources_date_status;
    }
    
    /**
     * @param budget_resources_date_status the budget_resources_date_status to set
     */
    public void setBudget_resources_date_status(Byte budget_resources_date_status) {
        this.budget_resources_date_status = budget_resources_date_status;
    }
    
    /**
     * @return the budget_resources_date_text
     */
    public String getBudget_resources_date_text() {
        return budget_resources_date_text;
    }
    
    /**
     * @param budget_resources_date_text the budget_resources_date_text to set
     */
    public void setBudget_resources_date_text(String budget_resources_date_text) {
        this.budget_resources_date_text = budget_resources_date_text;
    }
    
    /**
     * @return the changedirective_action
     */
    public String getChangedirective_action() {
        return changedirective_action;
    }
    
    /**
     * @param changedirective_action the changedirective_action to set
     */
    public void setChangedirective_action(String changedirective_action) {
        this.changedirective_action = changedirective_action;
    }
    
    /**
     * @return the changedirective_source
     */
    public String getChangedirective_source() {
        return changedirective_source;
    }
    
    /**
     * @param changedirective_source the changedirective_source to set
     */
    public void setChangedirective_source(String changedirective_source) {
        this.changedirective_source = changedirective_source;
    }
    
    /**
     * @return the changedirective_status
     */
    public Byte getChangedirective_status() {
        return changedirective_status;
    }
    
    /**
     * @param changedirective_status the changedirective_status to set
     */
    public void setChangedirective_status(Byte changedirective_status) {
        this.changedirective_status = changedirective_status;
    }
    
    /**
     * @return the changedirective_text
     */
    public String getChangedirective_text() {
        return changedirective_text;
    }
    
    /**
     * @param changedirective_text the changedirective_text to set
     */
    public void setChangedirective_text(String changedirective_text) {
        this.changedirective_text = changedirective_text;
    }
    
    /**
     * @return the communication_action
     */
    public String getCommunication_action() {
        return communication_action;
    }
    
    /**
     * @param communication_action the communication_action to set
     */
    public void setCommunication_action(String communication_action) {
        this.communication_action = communication_action;
    }
    
    /**
     * @return the communication_source
     */
    public String getCommunication_source() {
        return communication_source;
    }
    
    /**
     * @param communication_source the communication_source to set
     */
    public void setCommunication_source(String communication_source) {
        this.communication_source = communication_source;
    }
    
    /**
     * @return the communication_status
     */
    public Byte getCommunication_status() {
        return communication_status;
    }
    
    /**
     * @param communication_status the communication_status to set
     */
    public void setCommunication_status(Byte communication_status) {
        this.communication_status = communication_status;
    }
    
    /**
     * @return the communication_text
     */
    public String getCommunication_text() {
        return communication_text;
    }
    
    /**
     * @param communication_text the communication_text to set
     */
    public void setCommunication_text(String communication_text) {
        this.communication_text = communication_text;
    }
    
    /**
     * @return the created
     */
    public java.util.Date getCreated() {
        return created;
    }
    
    /**
     * @param created the created to set
     */
    public void setCreated(java.util.Date created) {
        this.created = created;
    }
    
    /**
     * @return the createdby
     */
    public String getCreatedby() {
        return createdby;
    }
    
    /**
     * @param createdby the createdby to set
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    
    /**
     * @return the customerorder
     */
    public Customerorder getCustomerorder() {
        return customerorder;
    }
    
    /**
     * @param customerorder the customerorder to set
     */
    public void setCustomerorder(Customerorder customerorder) {
        this.customerorder = customerorder;
    }
    
    /**
     * @return the fromdate
     */
    public java.sql.Date getFromdate() {
        return fromdate;
    }
    
    /**
     * @param fromdate the fromdate to set
     */
    public void setFromdate(java.sql.Date fromdate) {
        this.fromdate = fromdate;
    }
    
    /**
     * @return the id
     */
    public long getId() {
        return id;
    }
    
    /**
     * @param id the id to set
     */
    public void setId(long id) {
        this.id = id;
    }
    
    /**
     * @return the improvement_action
     */
    public String getImprovement_action() {
        return improvement_action;
    }
    
    /**
     * @param improvement_action the improvement_action to set
     */
    public void setImprovement_action(String improvement_action) {
        this.improvement_action = improvement_action;
    }
    
    /**
     * @return the improvement_source
     */
    public String getImprovement_source() {
        return improvement_source;
    }
    
    /**
     * @param improvement_source the improvement_source to set
     */
    public void setImprovement_source(String improvement_source) {
        this.improvement_source = improvement_source;
    }
    
    /**
     * @return the improvement_status
     */
    public Byte getImprovement_status() {
        return improvement_status;
    }
    
    /**
     * @param improvement_status the improvement_status to set
     */
    public void setImprovement_status(Byte improvement_status) {
        this.improvement_status = improvement_status;
    }
    
    /**
     * @return the improvement_text
     */
    public String getImprovement_text() {
        return improvement_text;
    }
    
    /**
     * @param improvement_text the improvement_text to set
     */
    public void setImprovement_text(String improvement_text) {
        this.improvement_text = improvement_text;
    }
    
    /**
     * @return the lastupdate
     */
    public java.util.Date getLastupdate() {
        return lastupdate;
    }
    
    /**
     * @param lastupdate the lastupdate to set
     */
    public void setLastupdate(java.util.Date lastupdate) {
        this.lastupdate = lastupdate;
    }
    
    /**
     * @return the lastupdatedby
     */
    public String getLastupdatedby() {
        return lastupdatedby;
    }
    
    /**
     * @param lastupdatedby the lastupdatedby to set
     */
    public void setLastupdatedby(String lastupdatedby) {
        this.lastupdatedby = lastupdatedby;
    }
    
    public String getCustomerfeedback_text() {
        return customerfeedback_text;
    }
    
    public void setCustomerfeedback_text(String customerfeedback_text) {
        this.customerfeedback_text = customerfeedback_text;
    }
    
    public String getCustomerfeedback_source() {
        return customerfeedback_source;
    }
    
    public void setCustomerfeedback_source(String customerfeedback_source) {
        this.customerfeedback_source = customerfeedback_source;
    }
    
    public Byte getCustomerfeedback_status() {
        return customerfeedback_status;
    }
    
    public void setCustomerfeedback_status(Byte customerfeedback_status) {
        this.customerfeedback_status = customerfeedback_status;
    }
    
    /**
     * @return the miscellaneous_action
     */
    public String getMiscellaneous_action() {
        return miscellaneous_action;
    }
    
    /**
     * @param miscellaneous_action the miscellaneous_action to set
     */
    public void setMiscellaneous_action(String miscellaneous_action) {
        this.miscellaneous_action = miscellaneous_action;
    }
    
    /**
     * @return the miscellaneous_source
     */
    public String getMiscellaneous_source() {
        return miscellaneous_source;
    }
    
    /**
     * @param miscellaneous_source the miscellaneous_source to set
     */
    public void setMiscellaneous_source(String miscellaneous_source) {
        this.miscellaneous_source = miscellaneous_source;
    }
    
    /**
     * @return the miscellaneous_status
     */
    public Byte getMiscellaneous_status() {
        return miscellaneous_status;
    }
    
    /**
     * @param miscellaneous_status the miscellaneous_status to set
     */
    public void setMiscellaneous_status(Byte miscellaneous_status) {
        this.miscellaneous_status = miscellaneous_status;
    }
    
    /**
     * @return the miscellaneous_text
     */
    public String getMiscellaneous_text() {
        return miscellaneous_text;
    }
    
    /**
     * @param miscellaneous_text the miscellaneous_text to set
     */
    public void setMiscellaneous_text(String miscellaneous_text) {
        this.miscellaneous_text = miscellaneous_text;
    }
    
    /**
     * @return the needforaction_source
     */
    public String getNeedforaction_source() {
        return needforaction_source;
    }
    
    /**
     * @param needforaction_source the needforaction_source to set
     */
    public void setNeedforaction_source(String needforaction_source) {
        this.needforaction_source = needforaction_source;
    }
    
    /**
     * @return the needforaction_status
     */
    public Byte getNeedforaction_status() {
        return needforaction_status;
    }
    
    /**
     * @param needforaction_status the needforaction_status to set
     */
    public void setNeedforaction_status(Byte needforaction_status) {
        this.needforaction_status = needforaction_status;
    }
    
    /**
     * @return the needforaction_text
     */
    public String getNeedforaction_text() {
        return needforaction_text;
    }
    
    /**
     * @param needforaction_text the needforaction_text to set
     */
    public void setNeedforaction_text(String needforaction_text) {
        this.needforaction_text = needforaction_text;
    }
    
    /**
     * @return the notes
     */
    public String getNotes() {
        return notes;
    }
    
    /**
     * @param notes the notes to set
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    /**
     * @return the phase
     */
    public Byte getPhase() {
        return phase;
    }
    
    /**
     * @param phase the phase to set
     */
    public void setPhase(Byte phase) {
        this.phase = phase;
    }
    
    /**
     * @return the recipient
     */
    public Employee getRecipient() {
        return recipient;
    }
    
    /**
     * @param recipient the recipient to set
     */
    public void setRecipient(Employee recipient) {
        this.recipient = recipient;
    }
    
    /**
     * @return the released
     */
    public java.util.Date getReleased() {
        return released;
    }
    
    /**
     * @param released the released to set
     */
    public void setReleased(java.util.Date released) {
        this.released = released;
    }
    
    /**
     * @return the releasedby
     */
    public Employee getReleasedby() {
        return releasedby;
    }
    
    /**
     * @param releasedby the releasedby to set
     */
    public void setReleasedby(Employee releasedby) {
        this.releasedby = releasedby;
    }
    
    /**
     * @return the riskmonitoring_action
     */
    public String getRiskmonitoring_action() {
        return riskmonitoring_action;
    }
    
    /**
     * @param riskmonitoring_action the riskmonitoring_action to set
     */
    public void setRiskmonitoring_action(String riskmonitoring_action) {
        this.riskmonitoring_action = riskmonitoring_action;
    }
    
    /**
     * @return the riskmonitoring_source
     */
    public String getRiskmonitoring_source() {
        return riskmonitoring_source;
    }
    
    /**
     * @param riskmonitoring_source the riskmonitoring_source to set
     */
    public void setRiskmonitoring_source(String riskmonitoring_source) {
        this.riskmonitoring_source = riskmonitoring_source;
    }
    
    /**
     * @return the riskmonitoring_status
     */
    public Byte getRiskmonitoring_status() {
        return riskmonitoring_status;
    }
    
    /**
     * @param riskmonitoring_status the riskmonitoring_status to set
     */
    public void setRiskmonitoring_status(Byte riskmonitoring_status) {
        this.riskmonitoring_status = riskmonitoring_status;
    }
    
    /**
     * @return the riskmonitoring_text
     */
    public String getRiskmonitoring_text() {
        return riskmonitoring_text;
    }
    
    /**
     * @param riskmonitoring_text the riskmonitoring_text to set
     */
    public void setRiskmonitoring_text(String riskmonitoring_text) {
        this.riskmonitoring_text = riskmonitoring_text;
    }
    
    /**
     * @return the sender
     */
    public Employee getSender() {
        return sender;
    }
    
    /**
     * @param sender the sender to set
     */
    public void setSender(Employee sender) {
        this.sender = sender;
    }
    
    /**
     * @return the sort
     */
    public Byte getSort() {
        return sort;
    }
    
    /**
     * @param sort the sort to set
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }
    
    /**
     * @return the trend
     */
    public Byte getTrend() {
        return trend;
    }
    
    /**
     * @param trend the trend to set
     */
    public void setTrend(Byte trend) {
        this.trend = trend;
    }
    
    /**
     * @return the trendstatus
     */
    public Byte getTrendstatus() {
        return trendstatus;
    }
    
    /**
     * @param trendstatus the trendstatus to set
     */
    public void setTrendstatus(Byte trendstatus) {
        this.trendstatus = trendstatus;
    }
    
    /**
     * @return the untildate
     */
    public java.sql.Date getUntildate() {
        return untildate;
    }
    
    /**
     * @param untildate the untildate to set
     */
    public void setUntildate(java.sql.Date untildate) {
        this.untildate = untildate;
    }
    
    /**
     * @return the updatecounter
     */
    public Integer getUpdatecounter() {
        return updatecounter;
    }
    
    /**
     * @param updatecounter the updatecounter to set
     */
    public void setUpdatecounter(Integer updatecounter) {
        this.updatecounter = updatecounter;
    }
    
    public Byte getOverallStatus() {
        Byte status = 0;
        if (getTrendstatus() > status) {
            status = getTrendstatus();
        }
        if (getNeedforaction_status() > status) {
            status = getNeedforaction_status();
        }
        if (getAim_status() > status) {
            status = getAim_status();
        }
        if (getBudget_resources_date_status() > status) {
            status = getBudget_resources_date_status();
        }
        if (getRiskmonitoring_status() > status) {
            status = getRiskmonitoring_status();
        }
        if (getChangedirective_status() > status) {
            status = getChangedirective_status();
        }
        if (getCommunication_status() > status) {
            status = getCommunication_status();
        }
        if (getImprovement_status() > status) {
            status = getImprovement_status();
        }
        if (getMiscellaneous_status() > status) {
            status = getMiscellaneous_status();
        }
        
        return status;
    }
    
}
