package org.tb.bdom;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Ticket implements Serializable {
    
    private static final long serialVersionUID = 1L; // 1L;
    
    /**
     * Autogenerated technical object id.
     */
    @Id
    @GeneratedValue
    private long id;
    
    /** Suborder */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "SUBORDER_ID")
    @Cascade(value = { CascadeType.SAVE_UPDATE })
    private Suborder suborder;
    
    /** Jira-Ticket-Key */
    @Column(name = "jira_Ticket_Key")
    private String jiraTicketKey;
    
    /** list of timereports, associated to this ticket */
    @OneToMany
    @Cascade(value = { CascadeType.SAVE_UPDATE })
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    private List<Timereport> timereports;
    
    /** from date */
    private Date fromDate;
    
    /** until date */
    private Date untilDate;
    
    /**
     * @return the id
     */
    public long getId() {
        return id;
    }
    
    /**
     * @param id - the id to set
     */
    public void setId(long id) {
        this.id = id;
    }
    
    /**
     * @return the suborder
     */
    public Suborder getSuborder() {
        return suborder;
    }
    
    /**
     * @param suborder - the suborder to set
     */
    public void setSuborder(Suborder suborder) {
        this.suborder = suborder;
    }
    
    public String getJiraTicketKey() {
        return jiraTicketKey;
    }
    
    public void setJiraTicketKey(String jiraTicketKey) {
        this.jiraTicketKey = jiraTicketKey;
    }
    
    public List<Timereport> getTimereports() {
        return timereports;
    }
    
    public void setTimereports(List<Timereport> timereports) {
        this.timereports = timereports;
    }
    
    public Date getFromDate() {
        return fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    
    public Date getUntilDate() {
        return untilDate;
    }
    
    public void setUntilDate(Date untilDate) {
        this.untilDate = untilDate;
    }
    
}
