package org.tb.bdom;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Worklog implements Serializable {
    
    private static final long serialVersionUID = 1L; // 1L;
    
    /**
     * Autogenerated technical object id.
     */
    @Id
    @GeneratedValue
    private long id;
    
    /** Jira-Worklog-ID */
    @Column(name = "jira_Worklog_ID")
    private int jiraWorklogID;
    
    /** Jira-Ticket-Key */
    @Column(name = "jira_Ticket_Key")
    private String jiraTicketKey;
    
    /** type of the worklogAction (created, updated)*/
    private String type;
    
    /** Timereport */
    @ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "TIMEREPORT_ID")
    @Cascade(value = { CascadeType.SAVE_UPDATE })
    private Timereport timereport;
    
    /** Update Counter */
    private Integer updatecounter;
    
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public int getJiraWorklogID() {
        return jiraWorklogID;
    }
    public void setJiraWorklogID(int jiraWorklogID) {
    	this.jiraWorklogID = jiraWorklogID;
    }
    public String getJiraTicketKey() {
        return jiraTicketKey;
    }
	public void setJiraTicketKey(String jiraTicketKey) {
		this.jiraTicketKey = jiraTicketKey;
	}
    public String getType() {
        return type;
    }
    public void setType(String type) {
        this.type = type;
    }
    public Timereport getTimereport() {
        return timereport;
    }
    public void setTimereport(Timereport timereport) {
        this.timereport = timereport;
    }
    public Integer getUpdatecounter() {
        return updatecounter;
    }
    public void setUpdatecounter(Integer updatecounter) {
        this.updatecounter = updatecounter;
    }
}
