package org.tb.bdom;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Bean for table 'customerorder'.
 * 
 * @author oda
 */
@Entity
public class Customerorder implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Autogenerated technical object id.
	 */	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;
	
	/** Customer */
	@ManyToOne
	@JoinColumn(name="CUSTOMER_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Customer customer;
	
	/** list of suborders, associated to this customerorder */
	@OneToMany(mappedBy = "customerorder")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private List<Suborder> suborders;
	
	/** Responsible of Customer */
	private String responsible_customer;
	
	/** Responsible of HBT */
	private String responsible_hbt;
	
	/** Orderer of Customer */
	private String order_customer;
	
	/** from date */
	private Date fromDate;
	
	/** until date */
	private Date untilDate;
	
	/** Sign */
	private String sign;
	
	/** Description */
	private String description;
	
	/** Currency */
	private String currency;

	/** Hourly Rate */
	private Double hourly_rate;
	
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getOrder_customer() {
		return order_customer;
	}

	public void setOrder_customer(String orderCustomer) {
		this.order_customer = orderCustomer;
	}

	public String getResponsible_customer() {
		return responsible_customer;
	}

	public void setResponsible_customer(String responsible_customer) {
		this.responsible_customer = responsible_customer;
	}

	public String getResponsible_hbt() {
		return responsible_hbt;
	}

	public void setResponsible_hbt(String responsible_hbt) {
		this.responsible_hbt = responsible_hbt;
	}

	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getUntilDate() {
		return untilDate;
	}

	public void setUntilDate(Date untilDate) {
		this.untilDate = untilDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Double getHourly_rate() {
		return hourly_rate;
	}

	public void setHourly_rate(Double hourly_rate) {
		this.hourly_rate = hourly_rate;
	}

	public List<Suborder> getSuborders() {
		return suborders;
	}

	public void setSuborders(List<Suborder> suborders) {
		this.suborders = suborders;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Customerorder) {
			Customerorder other = (Customerorder) obj;
			return other.getSign().equals(getSign());
		}
		return false;
	}

	@Override
	public int hashCode() {
		return getSign().hashCode();
	}

}
