package org.tb.bdom;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Bean for table 'invoice'.
 * 
 * @author oda
 */
@Entity
public class Invoice implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Autogenerated technical object id.
	 */	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;
	
	/** Customer */
	@ManyToOne
	@JoinColumn(name="CUSTOMER_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Customer customer;
	
	/** Description */
	private String description;
	
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Invoice) {
			Invoice other = (Invoice) obj;
			return other.getDescription().equals(getDescription());
		}
		return false;
	}

	@Override
	public int hashCode() {
		return getDescription().hashCode();
	}

}
