package org.tb.bdom;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Bean for table 'timereport'.
 * 
 * @author oda
 */
@Entity
public class Timereport implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Autogenerated technical object id.
	 */	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;

	/** Referenceday */
	@ManyToOne
	@JoinColumn(name="REFERENCEDAY_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Referenceday referenceday;
	
	/** Employeecontract */
	@ManyToOne
	@JoinColumn(name="EMPLOYEECONTRACT_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Employeecontract employeecontract;
	
	/** Suborder */
	@ManyToOne
	@JoinColumn(name="SUBORDER_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Suborder suborder;
	
	/** Hours/Minutes */
	private Double hours;
	private Integer beginhour;
	private Integer endhour;
	private Integer beginminute;
	private Integer endminute;
	
	/** Sort of Report */
	private String sortofreport;
	
	/** Task Description */
	private String taskdescription;
	
	/** Status */
	private String status;
	
	/** Costs */
	private Double costs;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}	
	
	public Employeecontract getEmployeecontract() {
		return employeecontract;
	}

	public void setEmployeecontract(Employeecontract employeecontract) {
		this.employeecontract = employeecontract;
	}

	public Double getHours() {
		return hours;
	}

	public void setHours(Double hours) {
		this.hours = hours;
	}
	
	public Integer getBeginhour() {
		return beginhour;
	}

	public void setBeginhour(Integer beginhour) {
		this.beginhour = beginhour;
	}

	public Integer getBeginminute() {
		return beginminute;
	}

	public void setBeginminute(Integer beginminute) {
		this.beginminute = beginminute;
	}

	public Integer getEndhour() {
		return endhour;
	}

	public void setEndhour(Integer endhour) {
		this.endhour = endhour;
	}

	public Integer getEndminute() {
		return endminute;
	}

	public void setEndminute(Integer endminute) {
		this.endminute = endminute;
	}
	
	public String getSortofreport() {
		return sortofreport;
	}

	public void setSortofreport(String sortofreport) {
		this.sortofreport = sortofreport;
	}

	public Referenceday getReferenceday() {
		return referenceday;
	}

	public void setReferenceday(Referenceday referenceday) {
		this.referenceday = referenceday;
	}

	public Suborder getSuborder() {
		return suborder;
	}

	public void setSuborder(Suborder order) {
		this.suborder = order;
	}
	
	public String getTaskdescription() {
		return taskdescription;
	}

	public void setTaskdescription(String taskdescription) {
		this.taskdescription = taskdescription;
	}

	public Double getCosts() {
		return costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
}
