package org.tb.bdom;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Bean for table 'timereport'.
 * 
 * @author oda
 */
@Entity
public class Timereport implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Autogenerated technical object id.
	 */	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;

	/** Referenceday */
	@ManyToOne
	@JoinColumn(name="REFERENCEDAY_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Referenceday referenceday;
	
	/** Employeecontract */
	@ManyToOne
	@JoinColumn(name="EMPLOYEECONTRACT_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Employeecontract employeecontract;
	
	/** Suborder */
	@ManyToOne
	@JoinColumn(name="SUBORDER_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Suborder suborder;
	
	/** Duration */
	private Integer durationhours;
	private Integer durationminutes;
	
	/** Sort of Report */
	private String sortofreport;
	
	/** Task Description */
	private String taskdescription;
	
	/** Status */
	private String status;
	
	/** Costs */
	private Double costs;
	
	/** Sequencial number */
	private int sequencenumber;
	
	
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}	
	
	public Employeecontract getEmployeecontract() {
		return employeecontract;
	}

	public void setEmployeecontract(Employeecontract employeecontract) {
		this.employeecontract = employeecontract;
	}

	public Integer getDurationhours() {
		return durationhours;
	}

	public void setDurationhours(Integer durationhours) {
		this.durationhours = durationhours;
	}
	
	public Integer getDurationminutes() {
		return durationminutes;
	}

	public void setDurationminutes(Integer durationminutes) {
		this.durationminutes = durationminutes;
	}

	public String getSortofreport() {
		return sortofreport;
	}

	public void setSortofreport(String sortofreport) {
		this.sortofreport = sortofreport;
	}

	public Referenceday getReferenceday() {
		return referenceday;
	}

	public void setReferenceday(Referenceday referenceday) {
		this.referenceday = referenceday;
	}

	public Suborder getSuborder() {
		return suborder;
	}

	public void setSuborder(Suborder order) {
		this.suborder = order;
	}
	
	public String getTaskdescription() {
		return taskdescription;
	}

	public void setTaskdescription(String taskdescription) {
		this.taskdescription = taskdescription;
	}

	public Double getCosts() {
		return costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the sequencenumber
	 */
	public int getSequencenumber() {
		return sequencenumber;
	}

	/**
	 * @param sequencenumber the sequencenumber to set
	 */
	public void setSequencenumber(int sequencenumber) {
		this.sequencenumber = sequencenumber;
	}

		
	
	
}
