package org.tb.bdom;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Bean for table 'worklogMemory'
 * 
 * @author jh
 *
 */
@Entity
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class WorklogMemory implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Autogenerated technical object id.
	 */	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;
	
	@Column(name = "operation")
	private int operation;
	
	@Column(name = "issue_ID")
	private String issueID;
	
	@Column(name = "worklog_ID")
	private int worklogID;
	
	@ManyToOne
    @Fetch(FetchMode.SELECT)
    @JoinColumn(name = "TIMEREPORT_ID")
    @Cascade(value = { CascadeType.SAVE_UPDATE })
	private Timereport timereport;

	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}

	public int getOperation() {
		return operation;
	}
	public void setOperation(int operation) {
		this.operation = operation;
	}

	public String getIssueID() {
		return issueID;
	}
	public void setIssueID(String issueID) {
		this.issueID = issueID;
	}

	public int getWorklogID() {
		return worklogID;
	}
	public void setWorklogID(int worklogID) {
		this.worklogID = worklogID;
	}
	
	public Timereport getTimereport() {
        return timereport;
    }
    public void setTimereport(Timereport timereport) {
        this.timereport = timereport;
    }
}
