package org.tb.bdom;

import java.io.Serializable;
import java.text.SimpleDateFormat;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;


@Entity
public class Workingday implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	/**
	 * Autogenerated technical object id.
	 */	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private long id;
	
	/** Employeecontract */
	@ManyToOne
	@JoinColumn(name="EMPLOYEECONTRACT_ID")
	@Cascade(value = { CascadeType.SAVE_UPDATE })
	private Employeecontract employeecontract;
	
	/** Date */
	private java.sql.Date refday;
	
	/** Starttimehour */
	private int Starttimehour;
	
	/** Starttimeminute */
	private int Starttimeminute;
	
	/** BreakHours */
	private int breakhours;
	
	/** BreakMinutes */
	private int breakminutes;
	
	
	/**
	 * @return the breakhours
	 */
	public int getBreakhours() {
		return breakhours;
	}

	/**
	 * @param breakhours the breakhours to set
	 */
	public void setBreakhours(int breakhours) {
		this.breakhours = breakhours;
	}

	/**
	 * @return the breakminutes
	 */
	public int getBreakminutes() {
		return breakminutes;
	}

	/**
	 * @param breakminutes the breakminutes to set
	 */
	public void setBreakminutes(int breakminutes) {
		this.breakminutes = breakminutes;
	}

	/**
	 * @return the employeecontract
	 */
	public Employeecontract getEmployeecontract() {
		return employeecontract;
	}

	/**
	 * @param employeecontract the employeecontract to set
	 */
	public void setEmployeecontract(Employeecontract employeecontract) {
		this.employeecontract = employeecontract;
	}

	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * @return the refday
	 */
	public java.sql.Date getRefday() {
		return refday;
	}

	/**
	 * @param refday the refdate to set
	 */
	public void setRefday(java.sql.Date refday) {
		this.refday = refday;
	}

	/**
	 * @return the starttimehour
	 */
	public int getStarttimehour() {
		return Starttimehour;
	}

	/**
	 * @param starttimehour the starttimehour to set
	 */
	public void setStarttimehour(int starttimehour) {
		Starttimehour = starttimehour;
	}

	/**
	 * @return the starttimeminute
	 */
	public int getStarttimeminute() {
		return Starttimeminute;
	}

	/**
	 * @param starttimeminute the starttimeminute to set
	 */
	public void setStarttimeminute(int starttimeminute) {
		Starttimeminute = starttimeminute;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Workingday) {
			Workingday other = (Workingday) obj;
			SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
			String refdateString = simpleDateFormat.format(refday);
			String otherString = simpleDateFormat.format(other.getRefday());
			
			return refdateString.equals(otherString) &&
				   employeecontract.getId() == other.getEmployeecontract().getId();
		}
		return false;
	}

	@Override
	public int hashCode() {
		return refday.hashCode() +
		       employeecontract.hashCode();
	}

}
