# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - salat-test

on:
  push:
    branches:
      - 240-azure-oauth2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ad436eae88da414398a774833aa7e13a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6195c39d1e244f3787e9a2ee69791b95 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_ad436eae88da414398a774833aa7e13a }}/hbtgmbh/salat:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'salat-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f561a282f4e24877a142b299f44e61d4 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_ad436eae88da414398a774833aa7e13a }}/hbtgmbh/salat:${{ github.sha }}'