name: Build .war and Docker container
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - assigned
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build with Maven
        run: ./mvnw -B package
      - name: Publish to Github
        run: ./mvnw -B -Dmaven.test.skip=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
      - name: Build Docker image
        run: ./mvnw -B -Dmaven.test.skip=true -Dspring-boot.build-image.imageName=ghcr.io/hbtgmbh/salat:ci spring-boot:build-image
      - name: Push Docker image with ci tag (required by tag-push-action)
        run: docker push ghcr.io/hbtgmbh/salat:ci
      - name: Push Docker image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/hbtgmbh/salat:ci
          dst: |
            ${{ steps.meta.outputs.tags }}
    
