name: Check Docker run
on:
  workflow_run:
    workflows:
      - Build .war and Docker container
    types:
      - completed
jobs:
  run:
    runs-on: ubuntu-latest
    services: 
      salat:
        image: ghcr.io/hbtgmbh/salat:main
        ports:
          - 8080:8080
    steps:
      - name: check that service is running
        run: http://localhost:8080/tb/
