name: Check Docker run
on:
  workflow_run:
    workflows:
      - Build .war and Docker container
    types:
      - completed
jobs:
  run:
    runs-on: ubuntu-latest
    container: ubuntu
    services: 
      salat:
        image: ghcr.io/hbtgmbh/salat:main
        ports:
          - 8080:8080
    steps:
      - run: apt-get update; apt-get install curl -y
      - run: curl -X GET salat:8080 > curl_result_docker
      - run: cat curl_result_docker
      - name: Check HTTP status
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["http://salat:8080/tb/"]'
          expected: '[200]'
