name: Check Docker run

on:
  workflow_call:
    inputs: 
      salat_tag:
        required: true
        type: string
      db_tag:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      db:
        image: ghcr.io/hbtgmbh/salat-testdb:${{ inputs.db_tag }}
      salat:
        image: ghcr.io/hbtgmbh/salat:${{ inputs.salat_tag }}
        ports:
          - 8080:8080
          - 8000:8000
        env:
          SPRING_DATASOURCE_USERNAME: salattest
          SPRING_DATASOURCE_PASSWORD: salattest
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/salat?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Berlin&useLegacyDatetimeCode=false&autoReconnect=true
          JPDA_ADDRESS: "*:8000"
    steps:
      - name: install curl
        run: apt-get update; apt-get install curl -y
      - name: run curl against salat
        run: curl -I salat:8080 | head -n 1 | cut -d ' ' -f2 > curl_result_docker
      - name: show result of curl
        run: cat curl_result_docker
      - name: is status code equal to 200?
        run: bash -c 'test $(<curl_result_docker) = "200"'

