name: Check Docker run
on:
  workflow_run:
    workflows:
      - Build .war and Docker container
    types:
      - completed
jobs:
  run:
    runs-on: ubuntu-latest
    services: 
      salat:
        image: ghcr.io/hbtgmbh/salat:main
        ports:
          - 80:80
    steps:
      - name: check that service is running
        run: http://localhost/tb/
