name: Check Docker run
on:
  workflow_run:
    workflows:
      - Build .war and Docker container
    types:
      - completed
jobs:
  run:
    runs-on: ubuntu-latest
    services: 
      salat:
        image: ghcr.io/hbtgmbh/salat:main
        ports:
          - 8080:8080
    steps:
      - name: Check that Salat is running
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["http://localhost:8080/tb/"]'
          expected: '[200]'
